"use client";
import Head from "next/head";
import { Inter } from "@next/font/google";

import { useRef, useState } from "react";
import BarcodeScanner from "@/components/BarcodeScanner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const scannerRef = useRef(null);
  return (
    <>
      <Head>
        <title>scanner-test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BarcodeScanner></BarcodeScanner>
    </>
  );
}
